"use client";

import { QueryClient, QueryClientProvider } from "react-query";

import type { Metadata } from "next";

import { TaskContextProvider } from "@/context/taskContext";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const queryClient = new QueryClient();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <QueryClientProvider client={queryClient}>
            <TaskContextProvider>{children}</TaskContextProvider>
          </QueryClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
